# Generated by Django 2.0.9 on 2019-03-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insaatWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maliyet_Projeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reelmaliyet', models.CharField(max_length=400, verbose_name='Reel Maliyet')),
                ('projeadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Projeler')),
            ],
        ),
    ]
