# Generated by Django 2.0.9 on 2019-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaatWeb', '0002_maliyet_projeler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maliyet_Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
            ],
        ),
    ]
