# Generated by Django 2.0.9 on 2019-03-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insaatWeb', '0003_maliyet_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maliyet_Kayit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birimfiyat', models.FloatField(blank=True, default=0, verbose_name='Birim Fiyatı')),
                ('adet', models.FloatField(blank=True, default=0, verbose_name='Adet')),
                ('hakkinda', models.CharField(blank=True, max_length=400, verbose_name='Hakkında')),
                ('ekleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Yonetici')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Maliyet_Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Maliyet_Madde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Maliyet_Kategori')),
            ],
        ),
        migrations.AddField(
            model_name='maliyet_kayit',
            name='maddeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Maliyet_Madde'),
        ),
        migrations.AddField(
            model_name='maliyet_kayit',
            name='projeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insaatWeb.Maliyet_Projeler'),
        ),
    ]
